files:
  include:
    - 'src/**/*.scss'
rules:
  class-name-format:
    - 1
    - convention: '^[A-Z][A-Za-z0-9]+(?:__[A-Za-z0-9\-]+)*(?:--[A-Za-z0-9\-]+)?$'
    - convention-explanation: "Class should be written in hyphenated BEM (Block Element Modifier) format"
  nesting-depth:
    - 1
    - max-depth: 3
  quotes:
    - 1
    - style: "double"
