files:
  include:
    - 'src/**/*.scss'
rules:
  class-name-format:
    - 1
    - convention: '^[A-Z][A-Za-z]+(?:__[A-Za-z]+)?(?:--[A-Za-z]+)?$'
    - convention-explanation: "Class should be written in hyphenated BEM (Block Element Modifier) format"
  quotes:
    - 1
    - style: "double"
