FROM electronuserland/builder:wine-chrome

# Install libsecret-1 and remove the apt-get cache afterwards
RUN apt-get update && apt-get install -y \
  libsecret-1-dev \
 && rm -rf /var/lib/apt/lists/*

ADD package.json /tmp/package.json
ADD package-lock.json /tmp/package-lock.json
RUN cd /tmp && npm install --quiet
RUN cp -a /tmp/node_modules /project/
