FROM centos:6

ENV NPM_CONFIG_UNSAFE_PERM true

RUN touch /var/lib/rpm/* \
 && yum -y install \
      centos-release-scl-rh \
      epel-release \
 && yum -y install \
      chrpath \
      devtoolset-3-binutils \
      devtoolset-3-gcc \
      devtoolset-3-gcc-c++ \
      jq \
      libconfig-devel \
      openssl-devel \
      python27 \
      wget \
      which \
 && yum clean all

RUN source /opt/rh/devtoolset-3/enable