export enum MainActions {
  AuthenticateWithEmail = 'authenticate-with-email',
  AuthenticateWithGitHub = 'authenticate-with-github',
  CheckForUpdates = 'check-for-updates',
  Deauthenticate = 'deauthenticate',
  RefreshCloudStatus = 'refresh-cloud-status',
  ReopenGitHubUrl = 'reopen-github-url',
  SetRaasEndpoint = 'set-raas-endpoint',
  ShowCloudAuthentication = 'show-cloud-authentication',
  ShowConnectToServer = 'show-connect-to-server',
  ShowGreeting = 'show-server-administration',
  ShowImportData = 'show-import-data',
  ShowOpenLocalRealm = 'show-open-local-realm',
  ShowRealmBrowser = 'show-realm-browser',
  ShowServerAdministration = 'show-server-administration',
  ShowTutorial = 'show-tutorial',
}
