export enum MainActions {
  AuthenticateWithGitHub = 'authenticate-with-github',
  Deauthenticate = 'deauthenticate',
  CheckForUpdates = 'check-for-updates',
  RefreshCloudStatus = 'refresh-cloud-status',
  SetRaasEndpoint = 'set-raas-endpoint',
  ShowConnectToServer = 'show-connect-to-server',
  ShowGreeting = 'show-server-administration',
  ShowImportData = 'show-import-data',
  ShowOpenLocalRealm = 'show-open-local-realm',
  ShowRealmBrowser = 'show-realm-browser',
  ShowServerAdministration = 'show-server-administration',
  ShowCloudAdministration = 'show-cloud-administration',
  ShowTutorial = 'show-tutorial',
}
